name: Build PDF Visual Editor x86 (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-i386:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      # Instalar Python 32 bits
      - name: Install Python 32-bit
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x86"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pdf_visual_editor/requirements.txt
          pip install pyinstaller

      - name: Build Windows 32-bit EXE
        working-directory: pdf_visual_editor
        shell: cmd
        run: build_exe.bat

      - name: Upload x86 artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-32bits
          path: dist/
