name: Build PDF Visual Editor for i386 (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-i386:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      # Instalar Python 32 bits
      - name: Install Python 32-bit
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x86"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pdf_visual_editor/requirements.txt
          pip install pyinstaller

      - name: Build i386 binary
        run: |
          pyinstaller pdf_visual_editor.spec

      - name: Upload i386 artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-i386
          path: dist/
