name: Build PDF Visual Editor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # ----------------------
  # Linux 64 bits
  # ----------------------
  build-linux-64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pdf_visual_editor/requirements.txt
          pip install pyinstaller PySide2

      - name: Build Linux 64-bit binary
        run: |
          chmod +x pdf_visual_editor/build_exe.sh
          pdf_visual_editor/build_exe.sh

      - name: Upload Linux 64-bit artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-64bit
          path: pdf_visual_editor/dist/

  # ----------------------
  # Linux 32 bits (Docker)
  # ----------------------
  build-linux-32:
    runs-on: ubuntu-latest
    container:
      image: 32bit/debian:jessie-armhf 

    steps:
      - uses: actions/checkout@v4

      - name: Install 32-bit Python and dependencies
        run: |
          # Habilitar soporte para arquitectura de 32 bits
          
          apt-get update

          # Instalar las dependencias necesarias para 32 bits
          apt-get install -y libc6 libstdc++6 python3.10 python3-pip

          # Asegurarse de usar la versi√≥n de Python de 32 bits
          python3.10 -m pip install --upgrade pip

      - name: Install project dependencies
        run: |
          # Usar el Python de 32 bits para instalar las dependencias del proyecto
          python3.10 -m pip install -r pdf_visual_editor/requirements.txt
          python3.10 -m pip install pyinstaller PySide2

      - name: Build Linux 32-bit binary
        run: |
          chmod +x pdf_visual_editor/build_exe.sh
          pyinstaller --distpath pdf_visual_editor/dist-i386 pdf_visual_editor/build_exe.spec

      - name: Upload Linux 32-bit artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-32bit
          path: pdf_visual_editor/dist-i386/

  # ----------------------
  # Windows 64 bits
  # ----------------------
  build-windows-64:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pdf_visual_editor\requirements.txt
          pip install pyinstaller PySide2

      - name: Build Windows 64-bit EXE
        run: pdf_visual_editor/build_exe.bat

      - name: Upload Windows 64-bit artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-64bit
          path: pdf_visual_editor/dist/
